fix: fit channel avatars to consistent size
pugson/react-farcaster-embed pull request #16
Opened 2024-10-02 15:55 UTC by zingerj

| Before | After |
|---|---|
| ![Capture-2024-10-02-114626](https://github.com/user-attachments/assets/e3e00873-236c-460d-a881-192b255cd0e7) | ![Capture-2024-10-02-114719](https://github.com/user-attachments/assets/d8b8c911-6d18-4cd8-a462-945ed74872d1) |

2024-10-02 19:36 UTC, pugson commented
this doesn't happen for me. are you sure you're not overriding some css properties?

2024-10-02 19:52 UTC, zingerj commented
I'm not touching any styles, just rendering the `<FarcasterEmbed />` directly. Have you tried specifically with the [/latenightcrew](https://warpcast.com/~/channel/latenightcrew) channel? It depends on the channel avatar, some are square so they just work.

2024-10-11 20:50 UTC, pugson requested changes

2024-10-11 20:50 UTC, pugson commented on src/styles.css
> +  background-color: red;
```suggestion
```

2024-10-11 20:59 UTC, pugson requested changes

2024-10-11 20:59 UTC, pugson commented on src/components/cast.tsx
> +                  <img src={cast.tags[0].imageUrl} alt={cast.tags[0].name} className="farcaster-embed-channel-avatar" />
```suggestion
                  <img src={cast.tags[0].imageUrl} alt={cast.tags[0].name} className="farcaster-embed-channel-avatar" width={16} height={16} />
```

2024-10-11 21:07 UTC, pugson approved these changes

2024-10-11 21:08 UTC, merged